name: Build and Publish
'on':
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: 'nixpkgs=channel:nixos-unstable'
      - name: Install dependencies
        run: |
          sudo apt-get install -y curl tar xz-utils
      - name: Build and Package
        run: >
          cd ./server

          nix-shell --command 'cargo build --release --target
          x86_64-unknown-linux-musl'

          strip -s target/x86_64-unknown-linux-musl/release/remote-party-finder
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Remote Party Finder
          path: >-
            ./server/target/x86_64-unknown-linux-musl/release/remote-party-finder
